trigger:
- main

pool: 
  name: Default

stages:
- stage: testing
  displayName: Test agent working
  jobs:
    - job: Test_build_image
      steps:
        - script: docker build -t test-agent .
          displayName: Build Image
        - script: docker image inspect test-agent
          displayName: Test image generation
        - script: echo $(variable_testing)
          displayName: Test env
        - script: docker rmi test-agent
          displayName: Delete image
        